#pragma once

#include "compiler/ilgen/J9ByteCodeIterator.hpp"
#include "compiler/optimizer/AbsVarArrayStatic.hpp"
#include "compiler/optimizer/AbsOpStackStatic.hpp"
#include "compiler/optimizer/VPConstraint.hpp"
#include "compiler/optimizer/ValuePropagation.hpp"
#include "compiler/optimizer/AbsValue.hpp"
#include "compiler/optimizer/IDT.hpp"
#include "compiler/infra/ILWalk.hpp"
#include "compiler/il/OMRBlock.hpp"
#include "il/Block.hpp"

class AbstractSemanticsImplicitArgument
{
public:
  virtual void aaload(){};
  virtual void aastore(){};
  virtual void aconstnull(){};
  virtual void aload(int){};
  virtual void aload0(){};
  virtual void aload0getfield(int){};
  virtual void aload1(){};
  virtual void aload2(){};
  virtual void aload3(){};
  virtual void anewarray(int){};
  virtual void areturn(){};
  virtual void arraylength(){};
  virtual void astore(int){};
  virtual void astore0(){};
  virtual void astore1(){};
  virtual void astore2(){};
  virtual void astore3(){};
  virtual void athrow(){};
  virtual void baload(){};
  virtual void bastore(){};
  virtual void bipush(int){};
  virtual void caload(){};
  virtual void castore(){};
  virtual void checkcast(int, int){};
  virtual void d2f(){};
  virtual void d2i(){};
  virtual void d2l(){};
  virtual void dadd(){};
  virtual void daload(){};
  virtual void dastore(){};
  virtual void dcmpl(){};
  virtual void dcmpg(){};
  virtual void dconst0(){};
  virtual void dconst1(){};
  virtual void ddiv(){};
  virtual void dload(int){};
  virtual void dload0(){};
  virtual void dload1(){};
  virtual void dload2(){};
  virtual void dload3(){};
  virtual void dmul(){};
  virtual void dneg(){};
  virtual void drem(){};
  virtual void dreturn(){};
  virtual void dstore(int){};
  virtual void dstore0(){};
  virtual void dstore1(){};
  virtual void dstore2(){};
  virtual void dstore3(){};
  virtual void dsub(){};
  virtual void dup(){};
  virtual void dupx1(){};
  virtual void dupx2(){};
  virtual void dup2(){};
  virtual void dup2x1(){};
  virtual void dup2x2(){};
  virtual void f2d(){};
  virtual void f2i(){};
  virtual void f2l(){};
  virtual void fadd(){};
  virtual void faload(){};
  virtual void fastore(){};
  virtual void fcmpl(){};
  virtual void fcmpg(){};
  virtual void fconst0(){};
  virtual void fconst1(){};
  virtual void fdiv(){};
  virtual void fload(int){};
  virtual void fload0(){};
  virtual void fload1(){};
  virtual void fload2(){};
  virtual void fload3(){};
  virtual void fmul(){};
  virtual void fneg(){};
  virtual void frem(){};
  virtual void freturn(){};
  virtual void fstore(int){};
  virtual void fstore0(){};
  virtual void fstore1(){};
  virtual void fstore2(){};
  virtual void fstore3(){};
  virtual void fsub(){};
  virtual void getfield(int){};
  virtual void getstatic(int){};
  virtual void _goto(int){};
  virtual void _gotow(int){};
  virtual void i2b(){};
  virtual void i2c(){};
  virtual void i2d(){};
  virtual void i2f(){};
  virtual void i2l(){};
  virtual void i2s(){};
  virtual void iadd(){};
  virtual void iaload(){};
  virtual void iand(){};
  virtual void iastore(){};
  virtual void iconstm1(){};
  virtual void iconst0(){};
  virtual void iconst1(){};
  virtual void iconst2(){};
  virtual void iconst3(){};
  virtual void iconst4(){};
  virtual void iconst5(){};
  virtual void idiv(){};
  virtual void ifacmpeq(int, int){};
  virtual void ifacmpne(int, int){};
  virtual void ificmpeq(int, int){};
  virtual void ificmpge(int, int){};
  virtual void ificmpgt(int, int){};
  virtual void ificmplt(int, int){};
  virtual void ificmple(int, int){};
  virtual void ificmpne(int, int){};
  virtual void ifeq(int, int){};
  virtual void ifge(int, int){};
  virtual void ifgt(int, int){};
  virtual void ifle(int, int){};
  virtual void iflt(int, int){};
  virtual void ifne(int, int){};
  virtual void ifnonnull(int, int){};
  virtual void ifnull(int, int){};
  virtual void iinc(int, int){};
  virtual void iload(int){};
  virtual void iload0(){};
  virtual void iload1(){};
  virtual void iload2(){};
  virtual void iload3(){};
  virtual void imul(){};
  virtual void ineg(){};
  virtual void instanceof(int, int){};
  virtual void invokedynamic(int, int){};
  virtual void invokeinterface(int, int){};
  virtual void invokespecial(int, int){};
  virtual void invokestatic(int, int){};
  virtual void invokevirtual(int, int){};
  virtual void ior(){};
  virtual void irem(){};
  //virtuavoidl  ireturn(){};
  virtual void ishl(){};
  virtual void ishr(){};
  virtual void istore(int){};
  virtual void istore0(){};
  virtual void istore1(){};
  virtual void istore2(){};
  virtual void istore3(){};
  virtual void isub(){};
  virtual void iushr(){};
  virtual void ixor(){};
  //virtuavoidl  jsr(){};
  //virtuavoidl  jsrw(){};
  virtual void l2d(){};
  virtual void l2f(){};
  virtual void l2i(){};
  virtual void ladd(){};
  virtual void laload(){};
  virtual void land(){};
  virtual void lastore(){};
  virtual void lcmp(){};
  virtual void lconst0(){};
  virtual void lconst1(){};
  virtual void ldc(int){};
  virtual void ldcw(int){};
  //virtuavoidl  ldc2w(int){};
  virtual void ldiv(){};
  virtual void lload(int){};
  virtual void lload0(){};
  virtual void lload1(){};
  virtual void lload2(){};
  virtual void lload3(){};
  virtual void lmul(){};
  virtual void lneg(){};
  virtual void lookupswitch(){};
  virtual void lor(){};
  virtual void lrem(){};
  //virtuavoidl  lreturn(){};
  virtual void lshl(){};
  virtual void lshr(){};
  virtual void lstore(int){};
  virtual void lstorew(int){};
  virtual void lstore0(){};
  virtual void lstore1(){};
  virtual void lstore2(){};
  virtual void lstore3(){};
  virtual void lsub(){};
  virtual void lushr(){};
  virtual void lxor(){};
  virtual void monitorenter(){};
  virtual void monitorexit(){};
  virtual void multianewarray(int, int){};
  virtual void _new(int){};
  virtual void newarray(int){};
  //virtuavoidl  nop(){};
  //virtuavoidl  pop(){};
  virtual void pop2(){};
  virtual void putfield(){};
  virtual void putstatic(){};
  //virtuavoidl  ret(){};
  //virtuavoidl  return(){};
  virtual void saload(){};
  virtual void sastore(){};
  virtual void sipush(int16_t){};
  virtual void swap(){};
  virtual void tableswitch(){};
  //virtuavoidl  wide(){};
};

template <class AbstractState>
class AbstractSemanticsImplicitReturn
{
public:
  virtual void aaload(AbstractState&) = 0;
  virtual void aastore(AbstractState&) = 0;
  virtual void aconstnull(AbstractState&) = 0;
  virtual void aload(AbstractState&, int) = 0;
  virtual void aload0(AbstractState&) = 0;
  virtual void aload0getfield(AbstractState&, int) = 0;
  virtual void aload1(AbstractState&) = 0;
  virtual void aload2(AbstractState&) = 0;
  virtual void aload3(AbstractState&) = 0;
  virtual void anewarray(AbstractState&, int) = 0;
  virtual void areturn(AbstractState&) = 0;
  virtual void arraylength(AbstractState&) = 0;
  virtual void astore(AbstractState&, int) = 0;
  virtual void astore0(AbstractState&) = 0;
  virtual void astore1(AbstractState&) = 0;
  virtual void astore2(AbstractState&) = 0;
  virtual void astore3(AbstractState&) = 0;
  virtual void athrow(AbstractState&) = 0;
  virtual void baload(AbstractState&) = 0;
  virtual void bastore(AbstractState&) = 0;
  virtual void bipush(AbstractState&, int) = 0;
  virtual void caload(AbstractState&) = 0;
  virtual void castore(AbstractState&) = 0;
  virtual void checkcast(AbstractState&, int, int) = 0;
  virtual void d2f(AbstractState&) = 0;
  virtual void d2i(AbstractState&) = 0;
  virtual void d2l(AbstractState&) = 0;
  virtual void dadd(AbstractState&) = 0;
  virtual void daload(AbstractState&) = 0;
  virtual void dastore(AbstractState&) = 0;
  virtual void dcmpl(AbstractState&) = 0;
  virtual void dcmpg(AbstractState&) = 0;
  virtual void dconst0(AbstractState&) = 0;
  virtual void dconst1(AbstractState&) = 0;
  virtual void ddiv(AbstractState&) = 0;
  virtual void dload(AbstractState&, int) = 0;
  virtual void dload0(AbstractState&) = 0;
  virtual void dload1(AbstractState&) = 0;
  virtual void dload2(AbstractState&) = 0;
  virtual void dload3(AbstractState&) = 0;
  virtual void dmul(AbstractState&) = 0;
  virtual void dneg(AbstractState&) = 0;
  virtual void drem(AbstractState&) = 0;
  virtual void dreturn(AbstractState&) = 0;
  virtual void dstore(AbstractState&, int) = 0;
  virtual void dstore0(AbstractState&) = 0;
  virtual void dstore1(AbstractState&) = 0;
  virtual void dstore2(AbstractState&) = 0;
  virtual void dstore3(AbstractState&) = 0;
  virtual void dsub(AbstractState&) = 0;
  virtual void dup(AbstractState&) = 0;
  virtual void dupx1(AbstractState&) = 0;
  virtual void dupx2(AbstractState&) = 0;
  virtual void dup2(AbstractState&) = 0;
  virtual void dup2x1(AbstractState&) = 0;
  virtual void dup2x2(AbstractState&) = 0;
  virtual void f2d(AbstractState&) = 0;
  virtual void f2i(AbstractState&) = 0;
  virtual void f2l(AbstractState&) = 0;
  virtual void fadd(AbstractState&) = 0;
  virtual void faload(AbstractState&) = 0;
  virtual void fastore(AbstractState&) = 0;
  virtual void fcmpl(AbstractState&) = 0;
  virtual void fcmpg(AbstractState&) = 0;
  virtual void fconst0(AbstractState&) = 0;
  virtual void fconst1(AbstractState&) = 0;
  virtual void fdiv(AbstractState&) = 0;
  virtual void fload(AbstractState&, int) = 0;
  virtual void fload0(AbstractState&) = 0;
  virtual void fload1(AbstractState&) = 0;
  virtual void fload2(AbstractState&) = 0;
  virtual void fload3(AbstractState&) = 0;
  virtual void fmul(AbstractState&) = 0;
  virtual void fneg(AbstractState&) = 0;
  virtual void frem(AbstractState&) = 0;
  virtual void freturn(AbstractState&) = 0;
  virtual void fstore(AbstractState&, int) = 0;
  virtual void fstore0(AbstractState&) = 0;
  virtual void fstore1(AbstractState&) = 0;
  virtual void fstore2(AbstractState&) = 0;
  virtual void fstore3(AbstractState&) = 0;
  virtual void fsub(AbstractState&) = 0;
  virtual void getfield(AbstractState&, int) = 0;
  virtual void getstatic(AbstractState&, int) = 0;
  virtual void _goto(AbstractState&, int) = 0;
  virtual void _gotow(AbstractState&, int) = 0;
  virtual void i2b(AbstractState&) = 0;
  virtual void i2c(AbstractState&) = 0;
  virtual void i2d(AbstractState&) = 0;
  virtual void i2f(AbstractState&) = 0;
  virtual void i2l(AbstractState&) = 0;
  virtual void i2s(AbstractState&) = 0;
  virtual void iadd(AbstractState&) = 0;
  virtual void iaload(AbstractState&) = 0;
  virtual void iand(AbstractState&) = 0;
  virtual void iastore(AbstractState&) = 0;
  virtual void iconstm1(AbstractState&) = 0;
  virtual void iconst0(AbstractState&) = 0;
  virtual void iconst1(AbstractState&) = 0;
  virtual void iconst2(AbstractState&) = 0;
  virtual void iconst3(AbstractState&) = 0;
  virtual void iconst4(AbstractState&) = 0;
  virtual void iconst5(AbstractState&) = 0;
  virtual void idiv(AbstractState&) = 0;
  virtual void ifacmpeq(AbstractState&, int, int) = 0;
  virtual void ifacmpne(AbstractState&, int, int) = 0;
  virtual void ificmpeq(AbstractState&, int, int) = 0;
  virtual void ificmpge(AbstractState&, int, int) = 0;
  virtual void ificmpgt(AbstractState&, int, int) = 0;
  virtual void ificmplt(AbstractState&, int, int) = 0;
  virtual void ificmple(AbstractState&, int, int) = 0;
  virtual void ificmpne(AbstractState&, int, int) = 0;
  virtual void ifeq(AbstractState&, int, int) = 0;
  virtual void ifge(AbstractState&, int, int) = 0;
  virtual void ifgt(AbstractState&, int, int) = 0;
  virtual void ifle(AbstractState&, int, int) = 0;
  virtual void iflt(AbstractState&, int, int) = 0;
  virtual void ifne(AbstractState&, int, int) = 0;
  virtual void ifnonnull(AbstractState&, int, int) = 0;
  virtual void ifnull(AbstractState&, int, int) = 0;
  virtual void iinc(AbstractState&, int, int) = 0;
  virtual void iload(AbstractState&, int) = 0;
  virtual void iload0(AbstractState&) = 0;
  virtual void iload1(AbstractState&) = 0;
  virtual void iload2(AbstractState&) = 0;
  virtual void iload3(AbstractState&) = 0;
  virtual void imul(AbstractState&) = 0;
  virtual void ineg(AbstractState&) = 0;
  virtual void instanceof(AbstractState&, int, int) = 0;
  virtual void invokedynamic(AbstractState&, int, int) = 0;
  virtual void invokeinterface(AbstractState&, int, int) = 0;
  virtual void invokespecial(AbstractState&, int, int) = 0;
  virtual void invokestatic(AbstractState&, int, int) = 0;
  virtual void invokevirtual(AbstractState&, int, int) = 0;
  virtual void ior(AbstractState&) = 0;
  virtual void irem(AbstractState&) = 0;
  //virtuavoidl  ireturn(AbstractState&) = 0;
  virtual void ishl(AbstractState&) = 0;
  virtual void ishr(AbstractState&) = 0;
  virtual void istore(AbstractState&, int) = 0;
  virtual void istore0(AbstractState&) = 0;
  virtual void istore1(AbstractState&) = 0;
  virtual void istore2(AbstractState&) = 0;
  virtual void istore3(AbstractState&) = 0;
  virtual void isub(AbstractState&) = 0;
  virtual void iushr(AbstractState&) = 0;
  virtual void ixor(AbstractState&) = 0;
  //virtuavoidl  jsr(AbstractState&) = 0;
  //virtuavoidl  jsrw(AbstractState&) = 0;
  virtual void l2d(AbstractState&) = 0;
  virtual void l2f(AbstractState&) = 0;
  virtual void l2i(AbstractState&) = 0;
  virtual void ladd(AbstractState&) = 0;
  virtual void laload(AbstractState&) = 0;
  virtual void land(AbstractState&) = 0;
  virtual void lastore(AbstractState&) = 0;
  virtual void lcmp(AbstractState&) = 0;
  virtual void lconst0(AbstractState&) = 0;
  virtual void lconst1(AbstractState&) = 0;
  virtual void ldc(AbstractState&, int) = 0;
  virtual void ldcw(AbstractState&, int) = 0;
  //virtuavoidl  ldc2w(AbstractState&int) = 0;
  virtual void ldiv(AbstractState&) = 0;
  virtual void lload(AbstractState&, int) = 0;
  virtual void lload0(AbstractState&) = 0;
  virtual void lload1(AbstractState&) = 0;
  virtual void lload2(AbstractState&) = 0;
  virtual void lload3(AbstractState&) = 0;
  virtual void lmul(AbstractState&) = 0;
  virtual void lneg(AbstractState&) = 0;
  virtual void lookupswitch(AbstractState&) = 0;
  virtual void lor(AbstractState&) = 0;
  virtual void lrem(AbstractState&) = 0;
  //virtuavoidl  lreturn(AbstractState&) = 0;
  virtual void lshl(AbstractState&) = 0;
  virtual void lshr(AbstractState&) = 0;
  virtual void lstore(AbstractState&, int) = 0;
  virtual void lstorew(AbstractState&, int) = 0;
  virtual void lstore0(AbstractState&) = 0;
  virtual void lstore1(AbstractState&) = 0;
  virtual void lstore2(AbstractState&) = 0;
  virtual void lstore3(AbstractState&) = 0;
  virtual void lsub(AbstractState&) = 0;
  virtual void lushr(AbstractState&) = 0;
  virtual void lxor(AbstractState&) = 0;
  virtual void monitorenter(AbstractState&) = 0;
  virtual void monitorexit(AbstractState&) = 0;
  virtual void multianewarray(AbstractState&, int, int) = 0;
  virtual void _new(AbstractState&, int) = 0;
  virtual void newarray(AbstractState&, int) = 0;
  //virtuavoidl  nop(AbstractState&) = 0;
  //virtuavoidl  pop(AbstractState&) = 0;
  virtual void pop2(AbstractState&) = 0;
  virtual void putfield(AbstractState&) = 0;
  virtual void putstatic(AbstractState&) = 0;
  //virtuavoidl  ret(AbstractState&) = 0;
  //virtuavoidl  return(AbstractState&) = 0;
  virtual void saload(AbstractState&) = 0;
  virtual void sastore(AbstractState&) = 0;
  virtual void sipush(AbstractState&, int16_t) = 0;
  virtual void swap(AbstractState&) = 0;
  virtual void tableswitch(AbstractState&) = 0;
  //virtuavoidl  wide(AbstractState&) = 0;
};

template <class AbstractState>
class AbstractSemanticsFunctional
{
public:
  virtual AbstractState& aaload(AbstractState&) = 0;
  virtual AbstractState& aastore(AbstractState&) = 0;
  virtual AbstractState& aconstnull(AbstractState&) = 0;
  virtual AbstractState& aload(AbstractState&, int) = 0;
  virtual AbstractState& aload0(AbstractState&) = 0;
  virtual AbstractState& aload0getfield(AbstractState&, int) = 0;
  virtual AbstractState& aload1(AbstractState&) = 0;
  virtual AbstractState& aload2(AbstractState&) = 0;
  virtual AbstractState& aload3(AbstractState&) = 0;
  virtual AbstractState& anewarray(AbstractState&, int) = 0;
  virtual AbstractState& areturn(AbstractState&) = 0;
  virtual AbstractState& arraylength(AbstractState&) = 0;
  virtual AbstractState& astore(AbstractState&, int) = 0;
  virtual AbstractState& astore0(AbstractState&) = 0;
  virtual AbstractState& astore1(AbstractState&) = 0;
  virtual AbstractState& astore2(AbstractState&) = 0;
  virtual AbstractState& astore3(AbstractState&) = 0;
  virtual AbstractState& athrow(AbstractState&) = 0;
  virtual AbstractState& baload(AbstractState&) = 0;
  virtual AbstractState& bastore(AbstractState&) = 0;
  virtual AbstractState& bipush(AbstractState&, int) = 0;
  virtual AbstractState& caload(AbstractState&) = 0;
  virtual AbstractState& castore(AbstractState&) = 0;
  virtual AbstractState& checkcast(AbstractState&, int, int) = 0;
  virtual AbstractState& d2f(AbstractState&) = 0;
  virtual AbstractState& d2i(AbstractState&) = 0;
  virtual AbstractState& d2l(AbstractState&) = 0;
  virtual AbstractState& dadd(AbstractState&) = 0;
  virtual AbstractState& daload(AbstractState&) = 0;
  virtual AbstractState& dastore(AbstractState&) = 0;
  virtual AbstractState& dcmpl(AbstractState&) = 0;
  virtual AbstractState& dcmpg(AbstractState&) = 0;
  virtual AbstractState& dconst0(AbstractState&) = 0;
  virtual AbstractState& dconst1(AbstractState&) = 0;
  virtual AbstractState& ddiv(AbstractState&) = 0;
  virtual AbstractState& dload(AbstractState&, int) = 0;
  virtual AbstractState& dload0(AbstractState&) = 0;
  virtual AbstractState& dload1(AbstractState&) = 0;
  virtual AbstractState& dload2(AbstractState&) = 0;
  virtual AbstractState& dload3(AbstractState&) = 0;
  virtual AbstractState& dmul(AbstractState&) = 0;
  virtual AbstractState& dneg(AbstractState&) = 0;
  virtual AbstractState& drem(AbstractState&) = 0;
  virtual AbstractState& dreturn(AbstractState&) = 0;
  virtual AbstractState& dstore(AbstractState&, int) = 0;
  virtual AbstractState& dstore0(AbstractState&) = 0;
  virtual AbstractState& dstore1(AbstractState&) = 0;
  virtual AbstractState& dstore2(AbstractState&) = 0;
  virtual AbstractState& dstore3(AbstractState&) = 0;
  virtual AbstractState& dsub(AbstractState&) = 0;
  virtual AbstractState& dup(AbstractState&) = 0;
  virtual AbstractState& dupx1(AbstractState&) = 0;
  virtual AbstractState& dupx2(AbstractState&) = 0;
  virtual AbstractState& dup2(AbstractState&) = 0;
  virtual AbstractState& dup2x1(AbstractState&) = 0;
  virtual AbstractState& dup2x2(AbstractState&) = 0;
  virtual AbstractState& f2d(AbstractState&) = 0;
  virtual AbstractState& f2i(AbstractState&) = 0;
  virtual AbstractState& f2l(AbstractState&) = 0;
  virtual AbstractState& fadd(AbstractState&) = 0;
  virtual AbstractState& faload(AbstractState&) = 0;
  virtual AbstractState& fastore(AbstractState&) = 0;
  virtual AbstractState& fcmpl(AbstractState&) = 0;
  virtual AbstractState& fcmpg(AbstractState&) = 0;
  virtual AbstractState& fconst0(AbstractState&) = 0;
  virtual AbstractState& fconst1(AbstractState&) = 0;
  virtual AbstractState& fdiv(AbstractState&) = 0;
  virtual AbstractState& fload(AbstractState&, int) = 0;
  virtual AbstractState& fload0(AbstractState&) = 0;
  virtual AbstractState& fload1(AbstractState&) = 0;
  virtual AbstractState& fload2(AbstractState&) = 0;
  virtual AbstractState& fload3(AbstractState&) = 0;
  virtual AbstractState& fmul(AbstractState&) = 0;
  virtual AbstractState& fneg(AbstractState&) = 0;
  virtual AbstractState& frem(AbstractState&) = 0;
  virtual AbstractState& freturn(AbstractState&) = 0;
  virtual AbstractState& fstore(AbstractState&, int) = 0;
  virtual AbstractState& fstore0(AbstractState&) = 0;
  virtual AbstractState& fstore1(AbstractState&) = 0;
  virtual AbstractState& fstore2(AbstractState&) = 0;
  virtual AbstractState& fstore3(AbstractState&) = 0;
  virtual AbstractState& fsub(AbstractState&) = 0;
  virtual AbstractState& getfield(AbstractState&, int) = 0;
  virtual AbstractState& getstatic(AbstractState&, int) = 0;
  virtual AbstractState& _goto(AbstractState&, int) = 0;
  virtual AbstractState& _gotow(AbstractState&, int) = 0;
  virtual AbstractState& i2b(AbstractState&) = 0;
  virtual AbstractState& i2c(AbstractState&) = 0;
  virtual AbstractState& i2d(AbstractState&) = 0;
  virtual AbstractState& i2f(AbstractState&) = 0;
  virtual AbstractState& i2l(AbstractState&) = 0;
  virtual AbstractState& i2s(AbstractState&) = 0;
  virtual AbstractState& iadd(AbstractState&) = 0;
  virtual AbstractState& iaload(AbstractState&) = 0;
  virtual AbstractState& iand(AbstractState&) = 0;
  virtual AbstractState& iastore(AbstractState&) = 0;
  virtual AbstractState& iconstm1(AbstractState&) = 0;
  virtual AbstractState& iconst0(AbstractState&) = 0;
  virtual AbstractState& iconst1(AbstractState&) = 0;
  virtual AbstractState& iconst2(AbstractState&) = 0;
  virtual AbstractState& iconst3(AbstractState&) = 0;
  virtual AbstractState& iconst4(AbstractState&) = 0;
  virtual AbstractState& iconst5(AbstractState&) = 0;
  virtual AbstractState& idiv(AbstractState&) = 0;
  virtual AbstractState& ifacmpeq(AbstractState&, int, int) = 0;
  virtual AbstractState& ifacmpne(AbstractState&, int, int) = 0;
  virtual AbstractState& ificmpeq(AbstractState&, int, int) = 0;
  virtual AbstractState& ificmpge(AbstractState&, int, int) = 0;
  virtual AbstractState& ificmpgt(AbstractState&, int, int) = 0;
  virtual AbstractState& ificmplt(AbstractState&, int, int) = 0;
  virtual AbstractState& ificmple(AbstractState&, int, int) = 0;
  virtual AbstractState& ificmpne(AbstractState&, int, int) = 0;
  virtual AbstractState& ifeq(AbstractState&, int, int) = 0;
  virtual AbstractState& ifge(AbstractState&, int, int) = 0;
  virtual AbstractState& ifgt(AbstractState&, int, int) = 0;
  virtual AbstractState& ifle(AbstractState&, int, int) = 0;
  virtual AbstractState& iflt(AbstractState&, int, int) = 0;
  virtual AbstractState& ifne(AbstractState&, int, int) = 0;
  virtual AbstractState& ifnonnull(AbstractState&, int, int) = 0;
  virtual AbstractState& ifnull(AbstractState&, int, int) = 0;
  virtual AbstractState& iinc(AbstractState&, int, int) = 0;
  virtual AbstractState& iload(AbstractState&, int) = 0;
  virtual AbstractState& iload0(AbstractState&) = 0;
  virtual AbstractState& iload1(AbstractState&) = 0;
  virtual AbstractState& iload2(AbstractState&) = 0;
  virtual AbstractState& iload3(AbstractState&) = 0;
  virtual AbstractState& imul(AbstractState&) = 0;
  virtual AbstractState& ineg(AbstractState&) = 0;
  virtual AbstractState& instanceof(AbstractState&, int, int) = 0;
  virtual AbstractState& invokedynamic(AbstractState&, int, int) = 0;
  virtual AbstractState& invokeinterface(AbstractState&, int, int) = 0;
  virtual AbstractState& invokespecial(AbstractState&, int, int) = 0;
  virtual AbstractState& invokestatic(AbstractState&, int, int) = 0;
  virtual AbstractState& invokevirtual(AbstractState&, int, int) = 0;
  virtual AbstractState& ior(AbstractState&) = 0;
  virtual AbstractState& irem(AbstractState&) = 0;
  //virtual AbstractState& ireturn(AbstractState&) = 0;
  virtual AbstractState& ishl(AbstractState&) = 0;
  virtual AbstractState& ishr(AbstractState&) = 0;
  virtual AbstractState& istore(AbstractState&, int) = 0;
  virtual AbstractState& istore0(AbstractState&) = 0;
  virtual AbstractState& istore1(AbstractState&) = 0;
  virtual AbstractState& istore2(AbstractState&) = 0;
  virtual AbstractState& istore3(AbstractState&) = 0;
  virtual AbstractState& isub(AbstractState&) = 0;
  virtual AbstractState& iushr(AbstractState&) = 0;
  virtual AbstractState& ixor(AbstractState&) = 0;
  //virtual AbstractState& jsr(AbstractState&) = 0;
  //virtual AbstractState& jsrw(AbstractState&) = 0;
  virtual AbstractState& l2d(AbstractState&) = 0;
  virtual AbstractState& l2f(AbstractState&) = 0;
  virtual AbstractState& l2i(AbstractState&) = 0;
  virtual AbstractState& ladd(AbstractState&) = 0;
  virtual AbstractState& laload(AbstractState&) = 0;
  virtual AbstractState& land(AbstractState&) = 0;
  virtual AbstractState& lastore(AbstractState&) = 0;
  virtual AbstractState& lcmp(AbstractState&) = 0;
  virtual AbstractState& lconst0(AbstractState&) = 0;
  virtual AbstractState& lconst1(AbstractState&) = 0;
  virtual AbstractState& ldc(AbstractState&, int) = 0;
  virtual AbstractState& ldcw(AbstractState&, int) = 0;
  //virtual AbstractState& ldc2w(AbstractState&int) = 0;
  virtual AbstractState& ldiv(AbstractState&) = 0;
  virtual AbstractState& lload(AbstractState&, int) = 0;
  virtual AbstractState& lload0(AbstractState&) = 0;
  virtual AbstractState& lload1(AbstractState&) = 0;
  virtual AbstractState& lload2(AbstractState&) = 0;
  virtual AbstractState& lload3(AbstractState&) = 0;
  virtual AbstractState& lmul(AbstractState&) = 0;
  virtual AbstractState& lneg(AbstractState&) = 0;
  virtual AbstractState& lookupswitch(AbstractState&) = 0;
  virtual AbstractState& lor(AbstractState&) = 0;
  virtual AbstractState& lrem(AbstractState&) = 0;
  //virtual AbstractState& lreturn(AbstractState&) = 0;
  virtual AbstractState& lshl(AbstractState&) = 0;
  virtual AbstractState& lshr(AbstractState&) = 0;
  virtual AbstractState& lstore(AbstractState&, int) = 0;
  virtual AbstractState& lstorew(AbstractState&, int) = 0;
  virtual AbstractState& lstore0(AbstractState&) = 0;
  virtual AbstractState& lstore1(AbstractState&) = 0;
  virtual AbstractState& lstore2(AbstractState&) = 0;
  virtual AbstractState& lstore3(AbstractState&) = 0;
  virtual AbstractState& lsub(AbstractState&) = 0;
  virtual AbstractState& lushr(AbstractState&) = 0;
  virtual AbstractState& lxor(AbstractState&) = 0;
  virtual AbstractState& monitorenter(AbstractState&) = 0;
  virtual AbstractState& monitorexit(AbstractState&) = 0;
  virtual AbstractState& multianewarray(AbstractState&, int, int) = 0;
  virtual AbstractState& _new(AbstractState&, int) = 0;
  virtual AbstractState& newarray(AbstractState&, int) = 0;
  //virtual AbstractState& nop(AbstractState&) = 0;
  //virtual AbstractState& pop(AbstractState&) = 0;
  virtual AbstractState& pop2(AbstractState&) = 0;
  virtual AbstractState& putfield(AbstractState&) = 0;
  virtual AbstractState& putstatic(AbstractState&) = 0;
  //virtual AbstractState& ret(AbstractState&) = 0;
  //virtual AbstractState& return(AbstractState&) = 0;
  virtual AbstractState& saload(AbstractState&) = 0;
  virtual AbstractState& sastore(AbstractState&) = 0;
  virtual AbstractState& sipush(AbstractState&, int16_t) = 0;
  virtual AbstractState& swap(AbstractState&) = 0;
  virtual AbstractState& tableswitch(AbstractState&) = 0;
  //virtual AbstractState& wide(AbstractState&) = 0;
};

//TODO: template over AbsValue
class AbstractState
{
public:
  AbstractState(TR::Region &region, IDT::Node *);
  AbstractState(const AbstractState&);
  void at(unsigned int, AbsValue*);
  AbsValue *at(unsigned int);
  void push(AbsValue *);
  AbsValue* pop();
  void merge(MergeOperation *op, const AbstractState &other);
  void merge(AbstractState &, TR::ValuePropagation*);
  size_t getStackSize() const;
  void trace(TR::ValuePropagation*);
  TR::Region &getRegion();
  AbsOpStackStatic _stack;
  AbsVarArrayStatic _array;
private:
  void enterMethod(TR::ResolvedMethodSymbol *);
  TR::Region &_region;
};

class AbsFrame;

class AbsEnvStatic : public AbstractSemanticsFunctional<AbstractState> {
public:
  AbsEnvStatic(TR::Region &region, IDT::Node *node, AbsFrame*);
  AbsEnvStatic(AbsEnvStatic&);
  void trace(const char* methodName = NULL);
  AbsEnvStatic *getWidened();
  void merge(AbsEnvStatic&);
  void interpret(TR_J9ByteCode, TR_J9ByteCodeIterator &);
  AbstractState &getState() { return this->_absState; }
  AbsFrame* getFrame() { return this->_absFrame; }
  static AbsEnvStatic *enterMethod(TR::Region&region, IDT::Node* node, AbsFrame* absFrame, TR::ResolvedMethodSymbol*);
  OMR::Block *getBlock() { return this->_block; }
  OMR::Block *_block;
  AbsValue *createAbsValue(TR::VPConstraint *vp, TR::DataType dt);
protected:
  AbsFrame* _absFrame;
  AbstractState _absState;
  AbsOpStackStatic & getStack();
  AbsVarArrayStatic & getArray();
  TR::Region &getRegion() const;
  TR::ResolvedMethodSymbol *getResolvedMethodSymbol() const;
  TR::ValuePropagation *getVP() const;
  IDT::Node *getNode() const;
  static AbsValue* getClassConstraint(TR_OpaqueClassBlock *, TR::ValuePropagation*, TR::Region&);

  virtual AbstractState& aaload(AbstractState&);
  virtual AbstractState& aastore(AbstractState&);
  virtual AbstractState& aconstnull(AbstractState&);
  virtual AbstractState& aload(AbstractState&, int);
  virtual AbstractState& aload0(AbstractState&);
  virtual AbstractState& aload0getfield(AbstractState&, int);
  virtual AbstractState& aload1(AbstractState&);
  virtual AbstractState& aload2(AbstractState&);
  virtual AbstractState& aload3(AbstractState&);
  virtual AbstractState& anewarray(AbstractState&, int);
  virtual AbstractState& areturn(AbstractState&);
  virtual AbstractState& arraylength(AbstractState&);
  virtual AbstractState& astore(AbstractState&, int);
  virtual AbstractState& astore0(AbstractState&);
  virtual AbstractState& astore1(AbstractState&);
  virtual AbstractState& astore2(AbstractState&);
  virtual AbstractState& astore3(AbstractState&);
  virtual AbstractState& athrow(AbstractState&);
  virtual AbstractState& baload(AbstractState&);
  virtual AbstractState& bastore(AbstractState&);
  virtual AbstractState& bipush(AbstractState&, int);
  virtual AbstractState& caload(AbstractState&);
  virtual AbstractState& castore(AbstractState&);
  virtual AbstractState& checkcast(AbstractState&, int, int);
  virtual AbstractState& d2f(AbstractState&);
  virtual AbstractState& d2i(AbstractState&);
  virtual AbstractState& d2l(AbstractState&);
  virtual AbstractState& dadd(AbstractState&);
  virtual AbstractState& daload(AbstractState&);
  virtual AbstractState& dastore(AbstractState&);
  virtual AbstractState& dcmpl(AbstractState&);
  virtual AbstractState& dcmpg(AbstractState&);
  virtual AbstractState& dconst0(AbstractState&);
  virtual AbstractState& dconst1(AbstractState&);
  virtual AbstractState& ddiv(AbstractState&);
  virtual AbstractState& dload(AbstractState&, int);
  virtual AbstractState& dload0(AbstractState&);
  virtual AbstractState& dload1(AbstractState&);
  virtual AbstractState& dload2(AbstractState&);
  virtual AbstractState& dload3(AbstractState&);
  virtual AbstractState& dmul(AbstractState&);
  virtual AbstractState& dneg(AbstractState&);
  virtual AbstractState& drem(AbstractState&);
  virtual AbstractState& dreturn(AbstractState&);
  virtual AbstractState& dstore(AbstractState&, int);
  virtual AbstractState& dstore0(AbstractState&);
  virtual AbstractState& dstore1(AbstractState&);
  virtual AbstractState& dstore2(AbstractState&);
  virtual AbstractState& dstore3(AbstractState&);
  virtual AbstractState& dsub(AbstractState&);
  virtual AbstractState& dup(AbstractState&);
  virtual AbstractState& dupx1(AbstractState&);
  virtual AbstractState& dupx2(AbstractState&);
  virtual AbstractState& dup2(AbstractState&);
  virtual AbstractState& dup2x1(AbstractState&);
  virtual AbstractState& dup2x2(AbstractState&);
  virtual AbstractState& f2d(AbstractState&);
  virtual AbstractState& f2i(AbstractState&);
  virtual AbstractState& f2l(AbstractState&);
  virtual AbstractState& fadd(AbstractState&);
  virtual AbstractState& faload(AbstractState&);
  virtual AbstractState& fastore(AbstractState&);
  virtual AbstractState& fcmpl(AbstractState&);
  virtual AbstractState& fcmpg(AbstractState&);
  virtual AbstractState& fconst0(AbstractState&);
  virtual AbstractState& fconst1(AbstractState&);
  virtual AbstractState& fdiv(AbstractState&);
  virtual AbstractState& fload(AbstractState&, int);
  virtual AbstractState& fload0(AbstractState&);
  virtual AbstractState& fload1(AbstractState&);
  virtual AbstractState& fload2(AbstractState&);
  virtual AbstractState& fload3(AbstractState&);
  virtual AbstractState& fmul(AbstractState&);
  virtual AbstractState& fneg(AbstractState&);
  virtual AbstractState& frem(AbstractState&);
  virtual AbstractState& freturn(AbstractState&);
  virtual AbstractState& fstore(AbstractState&, int);
  virtual AbstractState& fstore0(AbstractState&);
  virtual AbstractState& fstore1(AbstractState&);
  virtual AbstractState& fstore2(AbstractState&);
  virtual AbstractState& fstore3(AbstractState&);
  virtual AbstractState& fsub(AbstractState&);
  virtual AbstractState& getfield(AbstractState&, int);
  virtual AbstractState& getstatic(AbstractState&, int);
  virtual AbstractState& _goto(AbstractState&, int);
  virtual AbstractState& _gotow(AbstractState&, int);
  virtual AbstractState& i2b(AbstractState&);
  virtual AbstractState& i2c(AbstractState&);
  virtual AbstractState& i2d(AbstractState&);
  virtual AbstractState& i2f(AbstractState&);
  virtual AbstractState& i2l(AbstractState&);
  virtual AbstractState& i2s(AbstractState&);
  virtual AbstractState& iadd(AbstractState&);
  virtual AbstractState& iaload(AbstractState&);
  virtual AbstractState& iand(AbstractState&);
  virtual AbstractState& iastore(AbstractState&);
  virtual AbstractState& iconstm1(AbstractState&);
  virtual AbstractState& iconst0(AbstractState&);
  virtual AbstractState& iconst1(AbstractState&);
  virtual AbstractState& iconst2(AbstractState&);
  virtual AbstractState& iconst3(AbstractState&);
  virtual AbstractState& iconst4(AbstractState&);
  virtual AbstractState& iconst5(AbstractState&);
  virtual AbstractState& idiv(AbstractState&);
  virtual AbstractState& ifacmpeq(AbstractState&, int, int);
  virtual AbstractState& ifacmpne(AbstractState&, int, int);
  virtual AbstractState& ificmpeq(AbstractState&, int, int);
  virtual AbstractState& ificmpge(AbstractState&, int, int);
  virtual AbstractState& ificmpgt(AbstractState&, int, int);
  virtual AbstractState& ificmplt(AbstractState&, int, int);
  virtual AbstractState& ificmple(AbstractState&, int, int);
  virtual AbstractState& ificmpne(AbstractState&, int, int);
  virtual AbstractState& ifeq(AbstractState&, int, int);
  virtual AbstractState& ifge(AbstractState&, int, int);
  virtual AbstractState& ifgt(AbstractState&, int, int);
  virtual AbstractState& ifle(AbstractState&, int, int);
  virtual AbstractState& iflt(AbstractState&, int, int);
  virtual AbstractState& ifne(AbstractState&, int, int);
  virtual AbstractState& ifnonnull(AbstractState&, int, int);
  virtual AbstractState& ifnull(AbstractState&, int, int);
  virtual AbstractState& iinc(AbstractState&, int, int);
  virtual AbstractState& iload(AbstractState&, int);
  virtual AbstractState& iload0(AbstractState&);
  virtual AbstractState& iload1(AbstractState&);
  virtual AbstractState& iload2(AbstractState&);
  virtual AbstractState& iload3(AbstractState&);
  virtual AbstractState& imul(AbstractState&);
  virtual AbstractState& ineg(AbstractState&);
  virtual AbstractState& instanceof(AbstractState&, int, int);
  virtual AbstractState& invokedynamic(AbstractState&, int, int);
  virtual AbstractState& invokeinterface(AbstractState&, int, int);
  virtual AbstractState& invokespecial(AbstractState&, int, int);
  virtual AbstractState& invokestatic(AbstractState&, int, int);
  virtual AbstractState& invokevirtual(AbstractState&, int, int);
  virtual AbstractState& ior(AbstractState&);
  virtual AbstractState& irem(AbstractState&);
  //virtual AbstractState& ireturn(AbstractState&);
  virtual AbstractState& ishl(AbstractState&);
  virtual AbstractState& ishr(AbstractState&);
  virtual AbstractState& istore(AbstractState&, int);
  virtual AbstractState& istore0(AbstractState&);
  virtual AbstractState& istore1(AbstractState&);
  virtual AbstractState& istore2(AbstractState&);
  virtual AbstractState& istore3(AbstractState&);
  virtual AbstractState& isub(AbstractState&);
  virtual AbstractState& iushr(AbstractState&);
  virtual AbstractState& ixor(AbstractState&);
  //virtual AbstractState& jsr(AbstractState&);
  //virtual AbstractState& jsrw(AbstractState&);
  virtual AbstractState& l2d(AbstractState&);
  virtual AbstractState& l2f(AbstractState&);
  virtual AbstractState& l2i(AbstractState&);
  virtual AbstractState& ladd(AbstractState&);
  virtual AbstractState& laload(AbstractState&);
  virtual AbstractState& land(AbstractState&);
  virtual AbstractState& lastore(AbstractState&);
  virtual AbstractState& lcmp(AbstractState&);
  virtual AbstractState& lconst0(AbstractState&);
  virtual AbstractState& lconst1(AbstractState&);
  virtual AbstractState& ldc(AbstractState&, int);
  virtual AbstractState& ldcw(AbstractState&, int);
  //virtual AbstractState& ldc2w(AbstractState&int);
  virtual AbstractState& ldiv(AbstractState&);
  virtual AbstractState& lload(AbstractState&, int);
  virtual AbstractState& lload0(AbstractState&);
  virtual AbstractState& lload1(AbstractState&);
  virtual AbstractState& lload2(AbstractState&);
  virtual AbstractState& lload3(AbstractState&);
  virtual AbstractState& lmul(AbstractState&);
  virtual AbstractState& lneg(AbstractState&);
  virtual AbstractState& lookupswitch(AbstractState&);
  virtual AbstractState& lor(AbstractState&);
  virtual AbstractState& lrem(AbstractState&);
  //virtual AbstractState& lreturn(AbstractState&);
  virtual AbstractState& lshl(AbstractState&);
  virtual AbstractState& lshr(AbstractState&);
  virtual AbstractState& lstore(AbstractState&, int);
  virtual AbstractState& lstorew(AbstractState&, int);
  virtual AbstractState& lstore0(AbstractState&);
  virtual AbstractState& lstore1(AbstractState&);
  virtual AbstractState& lstore2(AbstractState&);
  virtual AbstractState& lstore3(AbstractState&);
  virtual AbstractState& lsub(AbstractState&);
  virtual AbstractState& lushr(AbstractState&);
  virtual AbstractState& lxor(AbstractState&);
  virtual AbstractState& monitorenter(AbstractState&);
  virtual AbstractState& monitorexit(AbstractState&);
  virtual AbstractState& multianewarray(AbstractState&, int, int);
  virtual AbstractState& _new(AbstractState&, int);
  virtual AbstractState& newarray(AbstractState&, int);
  //virtual AbstractState& nop(AbstractState&);
  //virtual AbstractState& pop(AbstractState&);
  virtual AbstractState& pop2(AbstractState&);
  virtual AbstractState& putfield(AbstractState&);
  virtual AbstractState& putstatic(AbstractState&);
  //virtual AbstractState& ret(AbstractState&);
  //virtual AbstractState& return(AbstractState&);
  virtual AbstractState& saload(AbstractState&);
  virtual AbstractState& sastore(AbstractState&);
  virtual AbstractState& sipush(AbstractState&, int16_t);
  virtual AbstractState& swap(AbstractState&);
  virtual AbstractState& tableswitch(AbstractState&);
  //virtual AbstractState& wide(AbstractState&);

private:

  // abstract interpreter helper
  void invoke(int, int, TR::MethodSymbol::Kinds);
  void aloadn(AbstractState&, int);
  void pushConstInt(AbstractState&, int);
  void interpretBlock(OMR::Block *block);
  void pushNull();
  void iconst(AbstractState&, int);
  void ldcString(int);
  void ldcAddress(int); 
  void ldcInt32(int); 
  void ldcInt64(int); 
  void ldcFloat();
  void ldcDouble();
  virtual AbsValue* getTopDataType(TR::DataType);
};

class AbsFrame
{
public:
  AbsFrame(TR::Region &region, IDT::Node *node);
  TR::ResolvedMethodSymbol *getResolvedMethodSymbol() const;
  TR::ValuePropagation* getValuePropagation() { return this->_vp; };
  virtual void interpret();
  TR::Region& getRegion() const { return this->_region; }
//TODO: move these to private...
  IDT::Node *_node;
  TR::ValuePropagation *_vp;
  TR_J9ByteCodeIterator _bci;
  void interpret(OMR::Block *);
  void interpret(OMR::Block *, AbsEnvStatic *); 
  virtual AbsValue *createAbsValue(TR::VPConstraint *vp, TR::DataType dt);
protected:
  TR::Region &_region;
  TR::ResolvedMethodSymbol *_rms;
  virtual void factFlow(OMR::Block *);
  virtual AbsEnvStatic *mergeAllPredecessors(OMR::Block *);
};

