#include "optimizer/IDTBuilder.hpp"
#include "optimizer/AbsInterpreter.hpp"

IDTBuilder::IDTBuilder(TR::ResolvedMethodSymbol* symbol, int32_t budget, TR::Region& region, TR::Compilation* comp, OMR::BenefitInliner* inliner) :
      _rootSymbol(symbol),
      _rootBudget(budget),
      _region(region),
      _comp(comp),
      _inliner(inliner),
      _idt(NULL),
      _util(NULL),
      _callSiteIndex(0),
      _interpretedMethodMap(InterpretedMethodMapComparator(), InterpretedMethodMapAllocator(region))
   {
   }

OMR::BenefitInlinerUtil* IDTBuilder::getUtil()
   {
   if (!_util)
      _util = new (comp()->allocator()) OMR::BenefitInlinerUtil(comp());
   return _util;
   }

//The CFG is generated from EstimateCodeSize. 
//The entry block has Node Number 2
//The exit block has Node Number 3
//The start block has Node Number 4
TR::CFG* IDTBuilder::generateFlowGraph(TR_CallTarget* callTarget, TR_InlinerBase* inliner, TR::Region& region, TR_CallStack* callStack)
   {
   TR_J9EstimateCodeSize* cfgGen = (TR_J9EstimateCodeSize *)TR_EstimateCodeSize::get(inliner, inliner->tracer(), 0);   
   TR::CFG* cfg = cfgGen->generateCFG(callTarget, callStack, region);
   callTarget->_calleeSymbol->setFlowGraph(cfg);
   //set the start block and exit block of the CFG
   // if (cfg)
   //    {
   //    TR::CFGNode* startNode = NULL;
   //    TR::CFGNode* exitNode = NULL;

   //    for (TR::CFGNode* node = cfg->getStart(); node; node = node->getNext())
   //       {
   //       if (node->getNumber() == 3)
   //          exitNode = node;
         
   //       if (node->getNumber() == 4)
   //          startNode = node;

   //       if (startNode && exitNode) //both are found
   //          break;
   //       }
      
   //    cfg->setStart(startNode);
   //    cfg->setEnd(exitNode);

   //    }
   return cfg;
   }


IDT* IDTBuilder::buildIDT()
   {
   bool traceBIIDTGen = comp()->getOption(TR_TraceBIIDTGen);

   if (traceBIIDTGen)
      traceMsg(comp(), "\n+ IDTBuilder: Start building IDT |\n\n");
   
   //root call target
   TR_ResolvedMethod* rootMethod = _rootSymbol->getResolvedMethod();
   TR_CallTarget *rootCallTarget = new (region()) TR_CallTarget(
                                    NULL,
                                    _rootSymbol, 
                                    rootMethod, 
                                    NULL, 
                                    rootMethod->containingClass(), 
                                    NULL);
   
   //Initialize IDT
   _idt = new (region()) IDT(region(), _rootSymbol, rootCallTarget, _rootBudget, comp());
   _idt->addCost(1);
   
   IDTNode* root = _idt->getRoot();

   //generate the CFG for root call target and 
   TR::CFG* cfg = generateFlowGraph(rootCallTarget, getInliner(), region());

   if (!cfg) //Fail to generate a CFG
      return _idt;

   //cfg->computeInitialBlockFrequencyBasedOnExternalProfiler(comp());
   cfg->setFrequencies();

   cfg->getAndSetStartBlockFrequency();
   // AbsInterpreter::setCFGBlockFrequency(cfg, true, comp());

   // traceMsg(comp(), "our cfg\n");
   // comp()->getDebug()->print(comp()->getOutFile(), cfg);
   
   //add the decendants
   buildIDTHelper(root, NULL, -1, _rootBudget, NULL);

   if (traceBIIDTGen)
      traceMsg(comp(), "\n+ IDTBuilder: Finish building IDT |\n");

   return _idt;
   }

void IDTBuilder::buildIDTHelper(IDTNode* node, AbsState* invokeState, int callerIndex, int32_t budget, TR_CallStack* callStack)
   {

   TR::ResolvedMethodSymbol* symbol = node->getResolvedMethodSymbol();
   TR_ResolvedMethod* method = symbol->getResolvedMethod();
   

   bool traceBIIDTGen = comp()->getOption(TR_TraceBIIDTGen);

   TR_CallStack* nextCallStack = new (region()) TR_CallStack(comp(), symbol, method, callStack, budget, true);

   IDTNode* interpretedMethodIDTNode = getInterpretedMethod(node->getResolvedMethodSymbol());
   
   if (interpretedMethodIDTNode)
      {
      node->setMethodSummary(interpretedMethodIDTNode->getMethodSummary());
      int staticBenefit = computeStaticBenefitWithMethodSummary(symbol->getMethod(), 
                                                               symbol->getMethodKind() == TR::MethodSymbol::Kinds::Static,
                                                               node->getMethodSummary(),  //use the method summary of the IDTNode with same method
                                                               invokeState);
      node->setStaticBenefit(staticBenefit);
      _idt->copyDescendants(interpretedMethodIDTNode, node); //IDT is built in DFS order, at this time, we have all the descendants so it is safe to copy the descendants
      return;
      }
   else
      {
      performAbstractInterpretation(node, callerIndex, nextCallStack);

      //At this point we have the method summary generated by abstract interpretation
      if (!node->isRoot())
         {
         int staticBenefit = computeStaticBenefitWithMethodSummary(symbol->getMethod(), 
                                                                     symbol->getMethodKind() == TR::MethodSymbol::Kinds::Static,
                                                                     node->getMethodSummary(), 
                                                                     invokeState);
         node->setStaticBenefit(staticBenefit); 
         }
      
      addInterpretedMethod(node->getResolvedMethodSymbol(), node); //store this method to already interpreted method map
      }
   
   return;
   }

//Abstract interpetation = Walk the bytecode + identifying invoke bytecode + update AbsState + generate method summary
void IDTBuilder::performAbstractInterpretation(IDTNode* node, int callerIndex, TR_CallStack* callStack)
   {
   AbsInterpreter interpreter(node, callerIndex, this, callStack, region(), comp());
   interpreter.interpret();
   }

IDTNode* IDTBuilder::getInterpretedMethod(TR::ResolvedMethodSymbol* symbol)
   {
   TR_ResolvedMethod* method = symbol->getResolvedMethod();
   TR_OpaqueMethodBlock* persistentIdentifier = method->getPersistentIdentifier();

   auto iter = _interpretedMethodMap.find(persistentIdentifier);
   if (iter == _interpretedMethodMap.end()) //Not interpreted yet
      return NULL;
   
   return iter->second;
   }

void IDTBuilder::addInterpretedMethod(TR::ResolvedMethodSymbol* symbol, IDTNode* node)
   {
   TR_ResolvedMethod* method = symbol->getResolvedMethod();
   TR_OpaqueMethodBlock* persistentIdentifier = method->getPersistentIdentifier();

   _interpretedMethodMap.insert(std::pair<TR_OpaqueMethodBlock *, IDTNode *>(persistentIdentifier,node));
   }

void IDTBuilder::addChild(IDTNode*node, int callerIndex, TR::Method* calleeMethod, bool isStaticMethod, TR_CallSite* callSite, AbsState* invokeState, TR_CallStack* callStack, TR::Block* block)
   {
   bool traceBIIDTGen = comp()->getOption(TR_TraceBIIDTGen);

   if (callSite == NULL)
      {
      cleanInvokeState(calleeMethod, isStaticMethod, invokeState); // pop parameters from Abs Op Stack to ensure the validness of Abs Op Stack
      return;
      }

   getInliner()->applyPolicyToTargets(callStack, callSite, block, node->getCallTarget()->_cfg); // eliminate call targets that are not inlinable thus they won't be added to IDT 

   if (callSite->numTargets() == 0) 
      {
      cleanInvokeState(calleeMethod, isStaticMethod, invokeState);
      return;
      }
      
   //There should be only one call Target in callsite (disable multiTargetInlining)
   //This must be changed if we want to enable multiTargetInlining later. 
   TR_CallTarget* callTarget = callSite->getTarget(0);

   int remainingBudget = node->getBudget() - callTarget->_calleeMethod->maxBytecodeIndex();
   if (remainingBudget < 0 ) // no budget remains, stop building IDT.
      {
      cleanInvokeState(calleeMethod, isStaticMethod, invokeState);
      return;
      }

   bool isRecursiveCall = callStack->isAnywhereOnTheStack(callTarget->_calleeMethod, 1);
   if (isRecursiveCall) //Stop for recursive call
      {
      cleanInvokeState(calleeMethod, isStaticMethod, invokeState);
      return;
      }
   
   TR::ResolvedMethodSymbol * calleeMethodSymbol = TR::ResolvedMethodSymbol::create(comp()->trHeapMemory(), callTarget->_calleeMethod, comp());

   //generate the CFG of this call target and set the block frequencies. 
   TR::CFG* cfg = generateFlowGraph(callTarget, getInliner(), region(), callStack);

   if (!cfg)
      {
      cleanInvokeState(calleeMethod, isStaticMethod, invokeState);
      return;
      }
   cfg->setFrequencies();

   //At this point we have the callsite, next thing is to compute the call ratio of the call target.
   float callRatio = computeCallRatio(callTarget, _callSiteIndex++, callStack, block, node->getCallTarget()->_cfg);

   
   //AbsInterpreter::setCFGBlockFrequency(cfg, false, comp());

   // traceMsg(comp(),"our cfg : %s\n", callTarget->signature(comp()->trMemory()));
   // comp()->getDebug()->print(comp()->getOutFile(), cfg);

   if (traceBIIDTGen)
      traceMsg(comp(), "+ IDTBuilder: Adding Child %s for IDTNode: %s\n",calleeMethod->signature(comp()->trMemory()), node->getName(comp()->trMemory()));

   IDTNode* child = node->addChild(
                           _idt->getNextGlobalIDTNodeIndex(),
                           callTarget,
                           callSite->_byteCodeIndex,
                           calleeMethodSymbol,
                           callRatio,
                           _idt->getMemoryRegion()
                           );
   if (traceBIIDTGen)
      traceMsg(comp(), child != NULL ? "success\n" : "fail\n");
   
   if (child == NULL) // Fail to add the Node to IDT
      {
     
      cleanInvokeState(calleeMethod, isStaticMethod, invokeState);
      return;
      }
   
   //If successfully add this child to the IDT
   _idt->increaseGlobalIDTNodeIndex();
   _idt->addCost(child->getCost());

   if (!comp()->incInlineDepth(calleeMethodSymbol, callSite->_bcInfo, callSite->_cpIndex, NULL, !callSite->isIndirectCall(), 0))
      {
      cleanInvokeState(calleeMethod, isStaticMethod, invokeState);
      return;
      }

   // Build the IDT recursively
   buildIDTHelper(child, invokeState, callerIndex + 1, child->getBudget(), callStack);

   comp()->decInlineDepth(true); 

   if (traceBIIDTGen)
      traceMsg(comp(), "+ IDTBuilder: add child: %s to parent: %s\n",child->getName(comp()->trMemory()),node->getName(comp()->trMemory()));
      
   }

float IDTBuilder::computeCallRatio(TR_CallTarget* callTarget, int callSiteIndex, TR_CallStack* callStack, TR::Block* block, TR::CFG* callerCfg)
   {
   TR_ASSERT_FATAL(callTarget, "Call Target is NULL!");
   
   TR::CFG* cfg = callTarget->_cfg;
   TR::ResolvedMethodSymbol *caller = callStack->_methodSymbol;
   
   //cfg->computeMethodBranchProfileInfo(getUtil(), callTarget, caller, callSiteIndex, block, callerCfg);
   // printf("++++ %s ++++ \n",callTarget->signature(comp()->trMemory()));
   // printf("%d: block %d, caller start block %d\n\n",block->getNumber(), block->getFrequency(),callerCfg->getStartBlockFrequency());
   int startBlockFrequency = callerCfg->getAndSetStartBlockFrequency();
   return ((float)block->getFrequency() / (float) startBlockFrequency);  
   }

void IDTBuilder::cleanInvokeState(TR::Method* calleeMethod, bool isStaticMethod, AbsState* invokeState)
   {
   computeStaticBenefitWithMethodSummary(calleeMethod, isStaticMethod, NULL, invokeState);
   }

int IDTBuilder::computeStaticBenefitWithMethodSummary(TR::Method* calleeMethod, bool isStaticMethod, MethodSummary* methodSummary, AbsState* invokeState)
   {
   TR_ASSERT_FATAL(invokeState, "invoke state is NULL");

   uint32_t numExplicitParams = calleeMethod->numberOfExplicitParameters();
   uint32_t numImplicitParams = isStaticMethod ? 0 : 1;
   uint32_t totalNumParams = numImplicitParams + numExplicitParams; 

   AbsValue *paramsArray[totalNumParams];

   for (uint32_t i = 0 ; i < numExplicitParams; i ++)
      {
      AbsValue* absValue = invokeState->pop();
      AbsValue* absValue2 = NULL;

      TR::DataType dataType = calleeMethod->parmType(numExplicitParams -i - 1);
      ////printf("Param %d, Type: %s\n",numExplicitParams -i - 1, TR::DataType::getName(dataType));
      if (dataType == TR::Double || dataType == TR::Int64)
         absValue2 = invokeState->pop();

      paramsArray[totalNumParams -i - 1] = absValue2 ? absValue2 : absValue;
      }

   if (numImplicitParams == 1)
      paramsArray[0] = invokeState->pop();

   if (methodSummary == NULL) //if we do not have method summary
      return 0;

   traceMsg(comp(), "## Compute static benefit of method: %s with method summary ##\n", calleeMethod->signature(comp()->trMemory()));

   int benefit = 0;

   for (uint32_t i = 0; i < totalNumParams; i ++)
      {
      AbsValue* value = paramsArray[i];
      benefit += methodSummary->predicates(value->getConstraint(), i);
      }
   // if (benefit > 2)
   //    printf("CAlleeMethid %s, benefit %d\n", calleeMethod->signature(comp()->trMemory()), benefit);
   return benefit;
   }

